print("jadilah seperti naruto walaupun bodoh tetapi menjadi HOKAGE")
print("jika kau menungguku menyerah, kau akan menunggu selamanya")
print("jika cintaku tidak diterima, akan kuhancurkan dunia")
print("kalau itu kenangan yang berarti, jangan dilupakan. sebab jika manusia mati, mereka hanya bisa hidup dalam kenangan orang lain")
print("lebih baik menerima kejujuran yang pahit, daripada kebohongan yang manis")
print("menang dan kalah membuatmu dewasa, menangislah dan bangkitlah")
print("kamu tidak akan mampu menghentikan orang yang sedang jatuh cinta kepada or0ng yang dia cintai")
print("jika kau seorang pria, buatlah wanita yang kau cintai jatuh cinta denganmu apapun yang terjadi")
print("jangan percaya kalau setiap yang berkacamata itu pintar")
print("kalau terus berfikir dan tak melakukan apa apa kamu akan tertinggal")
